server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          # uri: http://localhost:8001 注释写死的路由
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由

        - id: payment_route2
          # uri: http://localhost:8001 注释写死的路由
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

  instance:
    instance-id: cloud-gateway9527  #实例名称，注册到服务中心采用实例名称显示服务，不暴露带电脑主机名
    prefer-ip-address: true   #访问路径可以显示ip地址
    lease-renewal-interval-in-seconds: 30  #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认30秒）
    lease-expiration-duration-in-seconds: 90  #Eureka服务端在收到最后一次心跳等待时间上限，单位为秒（默认90秒），超时将删除服务