server:
  port: 8022


spring:
  application:
    name: nacos-elasticsearch
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"

