server:
  port: 80

spring:
  application:
    name: cloud-consumer-feign-hystrix-order

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

  instance:
    instance-id: feignHystrixOrder80  #实例名称，注册到服务中心采用实例名称显示服务，不暴露带电脑主机名
    prefer-ip-address: true   #访问路径可以显示ip地址
    lease-renewal-interval-in-seconds: 30  #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认30秒）
    lease-expiration-duration-in-seconds: 90  #Eureka服务端在收到最后一次心跳等待时间上限，单位为秒（默认90秒），超时将删除服务


feign:
  hystrix:
    # 在feign中开启Hystrix
    enabled: true